package eu.wohlben.qits.maintenance.api;

import static io.restassured.RestAssured.given;

import io.quarkus.test.junit.QuarkusTest;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.Test;

/**
 * Writes {@code docs/openapi.yml} as a side effect of the suite, the same way the sibling services
 * do: checking the document in turns an API change into a reviewable diff, and it is what a
 * consumer generates its client from (qits-landing-app's bumps menu, epic qits-112).
 *
 * <p>A test only because {@code @QuarkusTest} is the cheapest way to stand the application up and
 * read its own {@code /maintenance/q/openapi} — {@code quarkus.http.non-application-root-path}, not
 * {@code quarkus.rest.path}.
 *
 * <p>It asserts nothing — the assertion is the diff.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  @Test
  public void exportOpenApiSchema() throws Exception {
    String schema =
        given().when().get("/maintenance/q/openapi").then().statusCode(200).extract().asString();

    // The module is `service/`, so this resolves to the repo root's docs/.
    Path docsDir = Paths.get("../docs");
    if (!Files.exists(docsDir)) {
      Files.createDirectories(docsDir);
    }

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service -am test -Dtest=OpenApiSchemaExportTest"
            + " -Dsurefire.failIfNoSpecifiedTests=false` to regenerate.\n";

    Files.writeString(docsDir.resolve("openapi.yml"), header + schema);
  }
}
