package eu.wohlben.qits.maintenance.automation;

import eu.wohlben.qits.maintenance.bump.CiClient;
import eu.wohlben.qits.maintenance.githost.FileLookup;
import eu.wohlben.qits.maintenance.githost.TreeLookup;
import eu.wohlben.qits.maintenance.manifest.Xml;
import jakarta.enterprise.context.ApplicationScoped;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import org.w3c.dom.Element;

/**
 * <b>Entity diagram</b> (epic qits-760): regenerate {@code docs/database/*} — a Mermaid diagram of
 * a repository's JPA/Hibernate entities, generated by the {@code qits} CLI from compiled classes —
 * on every fold of every repository that has a database to draw.
 *
 * <h2>Applicability, read from the fold's poms and tree</h2>
 *
 * <p><b>The root pom decides first.</b> A repository with no {@code pom.xml} draws nothing: only
 * JPA/Hibernate is generated today, so NOT_APPLICABLE — unless its tree still carries a generated
 * diagram from before (see below). A repository WITH a root pom applies when the root, or one of
 * its reactor modules followed {@code <modules>} two levels deep, declares a {@code <dependency>}
 * whose {@code <artifactId>} is {@code quarkus-hibernate-orm}, {@code
 * quarkus-hibernate-orm-panache} or {@code hibernate-core}. The match is on the parsed element, with
 * external entities and the DOCTYPE off ({@link Xml}) — never a substring, so an artifactId sitting
 * only inside an XML comment never applies.
 *
 * <p><b>The tree is the second, cheaper check, and the one that lets the last entity be removed.</b>
 * A repository that dropped its ORM dependency — the last entity went with it — still carries a
 * generated {@code docs/database/*.md} from before. Regenerating it one more time is how it is
 * deleted: the generator owns its files and writes none this time, so it is removed. The same tree
 * read is what lets a repository with NO pom at all — not this estate's shape today, but the
 * interface does not assume one ORM forever — regenerate away a diagram it once had. One blob read
 * of the first {@code *.md} the listing holds settles it: its first line carries the generator's
 * header, {@code <!-- Generated by `qits database diagram` …}, or it does not.
 *
 * <p><b>Cost: at most one blob read of the root pom, one per module read (at most six on the
 * estate), and one tree read</b> — never more, and never a CI run for a repository the checks above
 * answer NOT_APPLICABLE for. A git-host read that does not answer makes the whole call UNKNOWN,
 * exactly as every other automation reads a fold.
 *
 * <h2>The carry-over invariant</h2>
 *
 * <p>{@code docs/database/**} is this kind's own output and NO kind's input — this one included.
 * The generator reads compiled classes, never its own written files, so the re-fold its own commit
 * causes changes nothing applicability or the plan would read differently: it is carried with no
 * second run, the same shape {@link EstatePinsAutomation} and {@link ScreenshotBaselinesAutomation}
 * keep for their own outputs.
 */
@ApplicationScoped
public class EntityDiagramAutomation implements ReleaseRequestAutomation {

  public static final String KIND = "entity-diagram";

  private static final String POM = "pom.xml";

  private static final String DOCS_DATABASE = "docs/database";

  /** The generated file's first line, as the CLI writes it (epic qits-760, Design §3). */
  static final String HEADER_PREFIX = "<!-- Generated by `qits database diagram`";

  private static final Set<String> ORM_ARTIFACTS =
      Set.of("quarkus-hibernate-orm", "quarkus-hibernate-orm-panache", "hibernate-core");

  private static final List<String> PATHS = List.of(":(glob)docs/database/**");

  private static final List<String> INPUTS = List.of(":(glob)**/*.java", ":(glob)**/pom.xml");

  @Override
  public String kind() {
    return KIND;
  }

  @Override
  public String label() {
    return "Entity diagram";
  }

  @Override
  public Applicability applicability(AutomationSubject subject) {
    FoldReader fold = subject.fold();
    FileLookup pom = fold.file(POM);
    return switch (pom.status()) {
      case FOUND -> {
        Applicability fromReactor = applicableFromReactor(fold, pom.content());
        yield fromReactor != null
            ? fromReactor
            : applicableFromGeneratedFiles(fold, "no JPA/Hibernate dependency");
      }
      case ABSENT ->
          applicableFromGeneratedFiles(
              fold, "no pom.xml: only JPA/Hibernate entity diagrams are generated");
      default -> Applicability.unknown(unread(POM, pom));
    };
  }

  @Override
  public String pipeline() {
    return CiClient.AUTOMATION_EVENT_NAME;
  }

  @Override
  public List<String> committablePaths() {
    return PATHS;
  }

  @Override
  public Target target() {
    return Target.OWN_BRANCH;
  }

  /** Generated from compiled classes, so from whatever the SOURCE kinds left the poms at. */
  @Override
  public Stage stage() {
    return Stage.DERIVED;
  }

  /**
   * What the generator reads: the sources it compiles and the poms that decide what it compiles
   * against (qits-1133). A fold that changed neither — a screenshot join, a lockfile, a README —
   * carries the previous fold's FRESH or COMMITTED outcome with no run.
   */
  @Override
  public List<String> inputPaths() {
    return INPUTS;
  }

  /**
   * The root pom and its reactor, followed {@code <modules>} two levels deep. {@code null} means
   * neither the root nor a module it could read declares the dependency — the caller falls back to
   * the tree check; a non-null answer is final (APPLIES, from a match, or UNKNOWN, from an
   * unreadable module).
   */
  private Applicability applicableFromReactor(FoldReader fold, String rootPomXml) {
    Element root = Xml.root(rootPomXml);
    if (root == null) {
      return null;
    }
    if (declaresOrm(root)) {
      return Applicability.applies();
    }
    for (String modulePath : modules(root)) {
      String modulePomPath = modulePath + "/" + POM;
      FileLookup modulePom = fold.file(modulePomPath);
      switch (modulePom.status()) {
        case FOUND -> {
          Element moduleRoot = Xml.root(modulePom.content());
          if (moduleRoot == null) {
            continue;
          }
          if (declaresOrm(moduleRoot)) {
            return Applicability.applies();
          }
          for (String subModulePath : modules(moduleRoot)) {
            String subPomPath = modulePath + "/" + subModulePath + "/" + POM;
            FileLookup subPom = fold.file(subPomPath);
            switch (subPom.status()) {
              case FOUND -> {
                Element subRoot = Xml.root(subPom.content());
                if (subRoot != null && declaresOrm(subRoot)) {
                  return Applicability.applies();
                }
              }
              case ABSENT -> {
                // No pom where a module was declared: nothing to read there.
              }
              default -> {
                return Applicability.unknown(unread(subPomPath, subPom));
              }
            }
          }
        }
        case ABSENT -> {
          // No pom where a module was declared: nothing to read there.
        }
        default -> {
          return Applicability.unknown(unread(modulePomPath, modulePom));
        }
      }
    }
    return null;
  }

  /**
   * Step 3: a generated diagram the fold's tree still carries, header and all — true whether or not
   * a pom was there, which is what lets the last entity's removal still regenerate (here, delete).
   */
  private Applicability applicableFromGeneratedFiles(FoldReader fold, String otherwiseReason) {
    TreeLookup tree = fold.tree(DOCS_DATABASE);
    return switch (tree.status()) {
      case FOUND -> {
        Optional<TreeLookup.TreeEntry> generated =
            tree.entries().stream()
                .filter(entry -> entry.isBlob() && entry.name().endsWith(".md"))
                .findFirst();
        if (generated.isEmpty()) {
          yield Applicability.notApplicable(otherwiseReason);
        }
        String path = DOCS_DATABASE + "/" + generated.get().name();
        FileLookup file = fold.file(path);
        yield switch (file.status()) {
          case FOUND ->
              firstLine(file.content()).startsWith(HEADER_PREFIX)
                  ? Applicability.applies()
                  : Applicability.notApplicable(otherwiseReason);
          case ABSENT -> Applicability.notApplicable(otherwiseReason);
          default -> Applicability.unknown(unread(path, file));
        };
      }
      case ABSENT -> Applicability.notApplicable(otherwiseReason);
      default -> Applicability.unknown(unread(DOCS_DATABASE, tree));
    };
  }

  /** Whether a parsed {@code <project>} declares one of the ORM artifacts as a live dependency. */
  private static boolean declaresOrm(Element project) {
    Element dependencies = Xml.child(project, "dependencies");
    for (Element dependency : Xml.children(dependencies, "dependency")) {
      String artifactId = Xml.childText(dependency, "artifactId");
      if (artifactId != null && ORM_ARTIFACTS.contains(artifactId.trim())) {
        return true;
      }
    }
    return false;
  }

  /** The {@code <modules>} a parsed {@code <project>} lists, in file order. */
  private static List<String> modules(Element project) {
    Element modulesElement = Xml.child(project, "modules");
    List<String> out = new ArrayList<>();
    for (Element module : Xml.children(modulesElement, "module")) {
      String text = Xml.text(module).trim();
      if (!text.isEmpty()) {
        out.add(text);
      }
    }
    return out;
  }

  private static String firstLine(String content) {
    if (content == null) {
      return "";
    }
    int newline = content.indexOf('\n');
    return (newline < 0 ? content : content.substring(0, newline)).stripTrailing();
  }

  private static String unread(String path, FileLookup lookup) {
    return lookup.message() == null
        ? path + " could not be read at the fold (" + lookup.status() + ")"
        : lookup.message();
  }

  private static String unread(String path, TreeLookup lookup) {
    return lookup.message() == null
        ? path + " could not be read at the fold (" + lookup.status() + ")"
        : lookup.message();
  }
}
